[package]
name = "philosophers_starvation"
version = "0.1.0"
authors = ["cpistillo <cpistillo@fi.uba.ar>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.6.0"
std-semaphore = "0.1.0"